name: NBA Bet - CI/CD

on:
  push:
    branches:
      - '*'

jobs:
  test:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests with coverage
        run: |
          pip install coverage
          coverage run -m unittest discover -s tests

      - name: Generate coverage report
        run: |
          coverage report
          coverage html

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          directory: ./htmlcov
          env_vars: OS,PYTHON
          fail_ci_if_error: true
          flags: unittests
          name: codecov-umbrella
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true

  build:
    name: Build Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t nba-bet:latest .
